@startuml

usecase c as "Calculer la paye"
usecase g as "Gérer un chantier"
usecase a as "Gérer les artisants"
usecase participer as "participer à un chantier"

actor Entreprise 
actor Artisant 
 
'Pour aligner les 2 acteurs :....0000
c -[hidden]-> a

Entreprise -> c
Entreprise -> g
Entreprise -> a

Artisant -> participer

@enduml